{"path":"backwards/src/test/org/apache/lucene/index/TestIndexWriterExceptions.IndexerThread#run().mjava","commits":[{"id":"480d01e5b0ef8efb136d51670fec297ae5ae2c9c","date":1268821447,"type":0,"author":"Uwe Schindler","isMerge":false,"pathNew":"backwards/src/test/org/apache/lucene/index/TestIndexWriterExceptions.IndexerThread#run().mjava","pathOld":"/dev/null","sourceNew":"    @Override\n    public void run() {\n\n      final Document doc = new Document();\n\n      doc.add(new Field(\"content1\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.ANALYZED));\n      doc.add(new Field(\"content6\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.ANALYZED, Field.TermVector.WITH_POSITIONS_OFFSETS));\n      doc.add(new Field(\"content2\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.NOT_ANALYZED));\n      doc.add(new Field(\"content3\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.NO));\n\n      doc.add(new Field(\"content4\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.ANALYZED));\n      doc.add(new Field(\"content5\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.NOT_ANALYZED));\n\n      doc.add(new Field(\"content7\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.NOT_ANALYZED, Field.TermVector.WITH_POSITIONS_OFFSETS));\n\n      final Field idField = new Field(\"id\", \"\", Field.Store.YES, Field.Index.NOT_ANALYZED);\n      doc.add(idField);\n\n      final long stopTime = System.currentTimeMillis() + 500;\n\n      do {\n        doFail.set(this);\n        final String id = \"\"+r.nextInt(50);\n        idField.setValue(id);\n        Term idTerm = new Term(\"id\", id);\n        try {\n          writer.updateDocument(idTerm, doc);\n        } catch (RuntimeException re) {\n          if (DEBUG) {\n            System.out.println(\"EXC: \");\n            re.printStackTrace(System.out);\n          }\n          try {\n            _TestUtil.checkIndex(writer.getDirectory());\n          } catch (IOException ioe) {\n            System.out.println(Thread.currentThread().getName() + \": unexpected exception1\");\n            ioe.printStackTrace(System.out);\n            failure = ioe;\n            break;\n          }\n        } catch (Throwable t) {\n          System.out.println(Thread.currentThread().getName() + \": unexpected exception2\");\n          t.printStackTrace(System.out);\n          failure = t;\n          break;\n        }\n\n        doFail.set(null);\n\n        // After a possible exception (above) I should be able\n        // to add a new document without hitting an\n        // exception:\n        try {\n          writer.updateDocument(idTerm, doc);\n        } catch (Throwable t) {\n          System.out.println(Thread.currentThread().getName() + \": unexpected exception3\");\n          t.printStackTrace(System.out);\n          failure = t;\n          break;\n        }\n      } while(System.currentTimeMillis() < stopTime);\n    }\n\n","sourceOld":null,"bugFix":null,"bugIntro":[],"isBuggy":false,"nexts":[],"revCommit":null},{"id":"9454a6510e2db155fb01faa5c049b06ece95fab9","date":1453508333,"type":5,"author":"Dawid Weiss","isMerge":false,"pathNew":"lucene/backwards/src/test/org/apache/lucene/index/TestIndexWriterExceptions.IndexerThread#run().mjava","pathOld":"backwards/src/test/org/apache/lucene/index/TestIndexWriterExceptions.IndexerThread#run().mjava","sourceNew":"    @Override\n    public void run() {\n\n      final Document doc = new Document();\n\n      doc.add(new Field(\"content1\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.ANALYZED));\n      doc.add(new Field(\"content6\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.ANALYZED, Field.TermVector.WITH_POSITIONS_OFFSETS));\n      doc.add(new Field(\"content2\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.NOT_ANALYZED));\n      doc.add(new Field(\"content3\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.NO));\n\n      doc.add(new Field(\"content4\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.ANALYZED));\n      doc.add(new Field(\"content5\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.NOT_ANALYZED));\n\n      doc.add(new Field(\"content7\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.NOT_ANALYZED, Field.TermVector.WITH_POSITIONS_OFFSETS));\n\n      final Field idField = new Field(\"id\", \"\", Field.Store.YES, Field.Index.NOT_ANALYZED);\n      doc.add(idField);\n\n      final long stopTime = System.currentTimeMillis() + 500;\n\n      do {\n        doFail.set(this);\n        final String id = \"\"+r.nextInt(50);\n        idField.setValue(id);\n        Term idTerm = new Term(\"id\", id);\n        try {\n          writer.updateDocument(idTerm, doc);\n        } catch (RuntimeException re) {\n          if (DEBUG) {\n            System.out.println(\"EXC: \");\n            re.printStackTrace(System.out);\n          }\n          try {\n            _TestUtil.checkIndex(writer.getDirectory());\n          } catch (IOException ioe) {\n            System.out.println(Thread.currentThread().getName() + \": unexpected exception1\");\n            ioe.printStackTrace(System.out);\n            failure = ioe;\n            break;\n          }\n        } catch (Throwable t) {\n          System.out.println(Thread.currentThread().getName() + \": unexpected exception2\");\n          t.printStackTrace(System.out);\n          failure = t;\n          break;\n        }\n\n        doFail.set(null);\n\n        // After a possible exception (above) I should be able\n        // to add a new document without hitting an\n        // exception:\n        try {\n          writer.updateDocument(idTerm, doc);\n        } catch (Throwable t) {\n          System.out.println(Thread.currentThread().getName() + \": unexpected exception3\");\n          t.printStackTrace(System.out);\n          failure = t;\n          break;\n        }\n      } while(System.currentTimeMillis() < stopTime);\n    }\n\n","sourceOld":"    @Override\n    public void run() {\n\n      final Document doc = new Document();\n\n      doc.add(new Field(\"content1\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.ANALYZED));\n      doc.add(new Field(\"content6\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.ANALYZED, Field.TermVector.WITH_POSITIONS_OFFSETS));\n      doc.add(new Field(\"content2\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.NOT_ANALYZED));\n      doc.add(new Field(\"content3\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.NO));\n\n      doc.add(new Field(\"content4\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.ANALYZED));\n      doc.add(new Field(\"content5\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.NOT_ANALYZED));\n\n      doc.add(new Field(\"content7\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.NOT_ANALYZED, Field.TermVector.WITH_POSITIONS_OFFSETS));\n\n      final Field idField = new Field(\"id\", \"\", Field.Store.YES, Field.Index.NOT_ANALYZED);\n      doc.add(idField);\n\n      final long stopTime = System.currentTimeMillis() + 500;\n\n      do {\n        doFail.set(this);\n        final String id = \"\"+r.nextInt(50);\n        idField.setValue(id);\n        Term idTerm = new Term(\"id\", id);\n        try {\n          writer.updateDocument(idTerm, doc);\n        } catch (RuntimeException re) {\n          if (DEBUG) {\n            System.out.println(\"EXC: \");\n            re.printStackTrace(System.out);\n          }\n          try {\n            _TestUtil.checkIndex(writer.getDirectory());\n          } catch (IOException ioe) {\n            System.out.println(Thread.currentThread().getName() + \": unexpected exception1\");\n            ioe.printStackTrace(System.out);\n            failure = ioe;\n            break;\n          }\n        } catch (Throwable t) {\n          System.out.println(Thread.currentThread().getName() + \": unexpected exception2\");\n          t.printStackTrace(System.out);\n          failure = t;\n          break;\n        }\n\n        doFail.set(null);\n\n        // After a possible exception (above) I should be able\n        // to add a new document without hitting an\n        // exception:\n        try {\n          writer.updateDocument(idTerm, doc);\n        } catch (Throwable t) {\n          System.out.println(Thread.currentThread().getName() + \": unexpected exception3\");\n          t.printStackTrace(System.out);\n          failure = t;\n          break;\n        }\n      } while(System.currentTimeMillis() < stopTime);\n    }\n\n","bugFix":null,"bugIntro":[],"isBuggy":false,"nexts":[],"revCommit":null}],"commit2Parents":{"480d01e5b0ef8efb136d51670fec297ae5ae2c9c":["a0e7ee9d0d12370e8d2b5ae0a23b6e687e018d85"],"a0e7ee9d0d12370e8d2b5ae0a23b6e687e018d85":[],"cd5edd1f2b162a5cfa08efd17851a07373a96817":["9454a6510e2db155fb01faa5c049b06ece95fab9"],"9454a6510e2db155fb01faa5c049b06ece95fab9":["480d01e5b0ef8efb136d51670fec297ae5ae2c9c"]},"commit2Childs":{"480d01e5b0ef8efb136d51670fec297ae5ae2c9c":["9454a6510e2db155fb01faa5c049b06ece95fab9"],"a0e7ee9d0d12370e8d2b5ae0a23b6e687e018d85":["480d01e5b0ef8efb136d51670fec297ae5ae2c9c"],"cd5edd1f2b162a5cfa08efd17851a07373a96817":[],"9454a6510e2db155fb01faa5c049b06ece95fab9":["cd5edd1f2b162a5cfa08efd17851a07373a96817"]},"heads":["cd5edd1f2b162a5cfa08efd17851a07373a96817"],"roots":["a0e7ee9d0d12370e8d2b5ae0a23b6e687e018d85"],"pathCommit":null}