{"path":"lucene/src/test-framework/java/org/apache/lucene/util/LuceneTestCase#tearDown().mjava","commits":[{"id":"7b91922b55d15444d554721b352861d028eb8278","date":1320421415,"type":1,"author":"Robert Muir","isMerge":false,"pathNew":"lucene/src/test-framework/java/org/apache/lucene/util/LuceneTestCase#tearDown().mjava","pathOld":"lucene/src/test-framework/org/apache/lucene/util/LuceneTestCase#tearDown().mjava","sourceNew":"  @After\n  public void tearDown() throws Exception {\n    State oldState = state; // capture test execution state\n    state = State.TEARDOWN; // set the state for subsequent tests\n    \n    // NOTE: with junit 4.7, we don't get a reproduceWith because our Watchman\n    // does not know if something fails in tearDown. so we ensure this happens ourselves for now.\n    // we can remove this if we upgrade to 4.8\n    Throwable problem = null;\n    \n    try {\n      if (!testsFailed) {\n        // Note: we allow a test to go straight from SETUP -> TEARDOWN (without ever entering the RANTEST state)\n        // because if you assume() inside setUp(), it skips the test and the TestWatchman has no way to know...\n        assertTrue(\"ensure your setUp() calls super.setUp()!!!\", oldState == State.RANTEST || oldState == State.SETUP);\n      }\n    } catch (Throwable t) {\n      if (problem == null) problem = t;\n    }\n\n    BooleanQuery.setMaxClauseCount(savedBoolMaxClauseCount);\n\n    // this won't throw any exceptions or fail the test\n    // if we change this, then change this logic\n    checkRogueThreadsAfter();\n    // restore the default uncaught exception handler\n    Thread.setDefaultUncaughtExceptionHandler(savedUncaughtExceptionHandler);\n    \n    try {\n      checkUncaughtExceptionsAfter();\n    } catch (Throwable t) {\n      if (problem == null) problem = t;\n    }\n    \n    try {\n      // calling assertSaneFieldCaches here isn't as useful as having test\n      // classes call it directly from the scope where the index readers\n      // are used, because they could be gc'ed just before this tearDown\n      // method is called.\n      //\n      // But it's better then nothing.\n      //\n      // If you are testing functionality that you know for a fact\n      // \"violates\" FieldCache sanity, then you should either explicitly\n      // call purgeFieldCache at the end of your test method, or refactor\n      // your Test class so that the inconsistant FieldCache usages are\n      // isolated in distinct test methods\n      assertSaneFieldCaches(getTestLabel());\n    } catch (Throwable t) {\n      if (problem == null) problem = t;\n    }\n    \n    purgeFieldCache(FieldCache.DEFAULT);\n    \n    if (problem != null) {\n      testsFailed = true;\n      reportAdditionalFailureInfo();\n      throw new RuntimeException(problem);\n    }\n  }\n\n","sourceOld":"  @After\n  public void tearDown() throws Exception {\n    State oldState = state; // capture test execution state\n    state = State.TEARDOWN; // set the state for subsequent tests\n    \n    // NOTE: with junit 4.7, we don't get a reproduceWith because our Watchman\n    // does not know if something fails in tearDown. so we ensure this happens ourselves for now.\n    // we can remove this if we upgrade to 4.8\n    Throwable problem = null;\n    \n    try {\n      if (!testsFailed) {\n        // Note: we allow a test to go straight from SETUP -> TEARDOWN (without ever entering the RANTEST state)\n        // because if you assume() inside setUp(), it skips the test and the TestWatchman has no way to know...\n        assertTrue(\"ensure your setUp() calls super.setUp()!!!\", oldState == State.RANTEST || oldState == State.SETUP);\n      }\n    } catch (Throwable t) {\n      if (problem == null) problem = t;\n    }\n\n    BooleanQuery.setMaxClauseCount(savedBoolMaxClauseCount);\n\n    // this won't throw any exceptions or fail the test\n    // if we change this, then change this logic\n    checkRogueThreadsAfter();\n    // restore the default uncaught exception handler\n    Thread.setDefaultUncaughtExceptionHandler(savedUncaughtExceptionHandler);\n    \n    try {\n      checkUncaughtExceptionsAfter();\n    } catch (Throwable t) {\n      if (problem == null) problem = t;\n    }\n    \n    try {\n      // calling assertSaneFieldCaches here isn't as useful as having test\n      // classes call it directly from the scope where the index readers\n      // are used, because they could be gc'ed just before this tearDown\n      // method is called.\n      //\n      // But it's better then nothing.\n      //\n      // If you are testing functionality that you know for a fact\n      // \"violates\" FieldCache sanity, then you should either explicitly\n      // call purgeFieldCache at the end of your test method, or refactor\n      // your Test class so that the inconsistant FieldCache usages are\n      // isolated in distinct test methods\n      assertSaneFieldCaches(getTestLabel());\n    } catch (Throwable t) {\n      if (problem == null) problem = t;\n    }\n    \n    purgeFieldCache(FieldCache.DEFAULT);\n    \n    if (problem != null) {\n      testsFailed = true;\n      reportAdditionalFailureInfo();\n      throw new RuntimeException(problem);\n    }\n  }\n\n","bugFix":null,"bugIntro":[],"isBuggy":false,"nexts":[],"revCommit":null},{"id":"3a119bbc8703c10faa329ec201c654b3a35a1e3e","date":1328644745,"type":5,"author":"Steven Rowe","isMerge":false,"pathNew":"lucene/test-framework/src/java/org/apache/lucene/util/LuceneTestCase#tearDown().mjava","pathOld":"lucene/src/test-framework/java/org/apache/lucene/util/LuceneTestCase#tearDown().mjava","sourceNew":"  @After\n  public void tearDown() throws Exception {\n    State oldState = state; // capture test execution state\n    state = State.TEARDOWN; // set the state for subsequent tests\n    \n    // NOTE: with junit 4.7, we don't get a reproduceWith because our Watchman\n    // does not know if something fails in tearDown. so we ensure this happens ourselves for now.\n    // we can remove this if we upgrade to 4.8\n    Throwable problem = null;\n    \n    try {\n      if (!testsFailed) {\n        // Note: we allow a test to go straight from SETUP -> TEARDOWN (without ever entering the RANTEST state)\n        // because if you assume() inside setUp(), it skips the test and the TestWatchman has no way to know...\n        assertTrue(\"ensure your setUp() calls super.setUp()!!!\", oldState == State.RANTEST || oldState == State.SETUP);\n      }\n    } catch (Throwable t) {\n      if (problem == null) problem = t;\n    }\n\n    BooleanQuery.setMaxClauseCount(savedBoolMaxClauseCount);\n\n    // this won't throw any exceptions or fail the test\n    // if we change this, then change this logic\n    checkRogueThreadsAfter();\n    // restore the default uncaught exception handler\n    Thread.setDefaultUncaughtExceptionHandler(savedUncaughtExceptionHandler);\n    \n    try {\n      checkUncaughtExceptionsAfter();\n    } catch (Throwable t) {\n      if (problem == null) problem = t;\n    }\n    \n    try {\n      // calling assertSaneFieldCaches here isn't as useful as having test\n      // classes call it directly from the scope where the index readers\n      // are used, because they could be gc'ed just before this tearDown\n      // method is called.\n      //\n      // But it's better then nothing.\n      //\n      // If you are testing functionality that you know for a fact\n      // \"violates\" FieldCache sanity, then you should either explicitly\n      // call purgeFieldCache at the end of your test method, or refactor\n      // your Test class so that the inconsistant FieldCache usages are\n      // isolated in distinct test methods\n      assertSaneFieldCaches(getTestLabel());\n    } catch (Throwable t) {\n      if (problem == null) problem = t;\n    }\n    \n    purgeFieldCache(FieldCache.DEFAULT);\n    \n    if (problem != null) {\n      testsFailed = true;\n      reportAdditionalFailureInfo();\n      throw new RuntimeException(problem);\n    }\n  }\n\n","sourceOld":"  @After\n  public void tearDown() throws Exception {\n    State oldState = state; // capture test execution state\n    state = State.TEARDOWN; // set the state for subsequent tests\n    \n    // NOTE: with junit 4.7, we don't get a reproduceWith because our Watchman\n    // does not know if something fails in tearDown. so we ensure this happens ourselves for now.\n    // we can remove this if we upgrade to 4.8\n    Throwable problem = null;\n    \n    try {\n      if (!testsFailed) {\n        // Note: we allow a test to go straight from SETUP -> TEARDOWN (without ever entering the RANTEST state)\n        // because if you assume() inside setUp(), it skips the test and the TestWatchman has no way to know...\n        assertTrue(\"ensure your setUp() calls super.setUp()!!!\", oldState == State.RANTEST || oldState == State.SETUP);\n      }\n    } catch (Throwable t) {\n      if (problem == null) problem = t;\n    }\n\n    BooleanQuery.setMaxClauseCount(savedBoolMaxClauseCount);\n\n    // this won't throw any exceptions or fail the test\n    // if we change this, then change this logic\n    checkRogueThreadsAfter();\n    // restore the default uncaught exception handler\n    Thread.setDefaultUncaughtExceptionHandler(savedUncaughtExceptionHandler);\n    \n    try {\n      checkUncaughtExceptionsAfter();\n    } catch (Throwable t) {\n      if (problem == null) problem = t;\n    }\n    \n    try {\n      // calling assertSaneFieldCaches here isn't as useful as having test\n      // classes call it directly from the scope where the index readers\n      // are used, because they could be gc'ed just before this tearDown\n      // method is called.\n      //\n      // But it's better then nothing.\n      //\n      // If you are testing functionality that you know for a fact\n      // \"violates\" FieldCache sanity, then you should either explicitly\n      // call purgeFieldCache at the end of your test method, or refactor\n      // your Test class so that the inconsistant FieldCache usages are\n      // isolated in distinct test methods\n      assertSaneFieldCaches(getTestLabel());\n    } catch (Throwable t) {\n      if (problem == null) problem = t;\n    }\n    \n    purgeFieldCache(FieldCache.DEFAULT);\n    \n    if (problem != null) {\n      testsFailed = true;\n      reportAdditionalFailureInfo();\n      throw new RuntimeException(problem);\n    }\n  }\n\n","bugFix":null,"bugIntro":[],"isBuggy":false,"nexts":[],"revCommit":null}],"commit2Parents":{"7b91922b55d15444d554721b352861d028eb8278":["a0e7ee9d0d12370e8d2b5ae0a23b6e687e018d85"],"3a119bbc8703c10faa329ec201c654b3a35a1e3e":["7b91922b55d15444d554721b352861d028eb8278"],"a0e7ee9d0d12370e8d2b5ae0a23b6e687e018d85":[],"cd5edd1f2b162a5cfa08efd17851a07373a96817":["3a119bbc8703c10faa329ec201c654b3a35a1e3e"]},"commit2Childs":{"7b91922b55d15444d554721b352861d028eb8278":["3a119bbc8703c10faa329ec201c654b3a35a1e3e"],"3a119bbc8703c10faa329ec201c654b3a35a1e3e":["cd5edd1f2b162a5cfa08efd17851a07373a96817"],"a0e7ee9d0d12370e8d2b5ae0a23b6e687e018d85":["7b91922b55d15444d554721b352861d028eb8278"],"cd5edd1f2b162a5cfa08efd17851a07373a96817":[]},"heads":["cd5edd1f2b162a5cfa08efd17851a07373a96817"],"roots":["a0e7ee9d0d12370e8d2b5ae0a23b6e687e018d85"],"pathCommit":null}